version: '3.9'

services:
  viasoft-app:
    build: .
    ports:
      - "5001:5001" 
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}  
      - DB_PORT=${DB_PORT}      
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE} 
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: viasoft-db
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_DATABASE} 